### ISSUE TITLE
Fix broken Controlled Component when using Asynchronous Unstated

### ISSUE THREAD

**Issue by johnbrett** [paul-phan/unstated-x#1]
> Fix broken Controlled Component when using Asynchronous Unstated

Have you any details on what's broken or why @paul-phan ?

**Comment by paul-phan** [comment]
Hi @johnbrett, Actually I just like the initial idea of `unstated` when their `setState` is just working synchronously.
As you can see in the `Subscribe` component, they already call React `setState` in `onUpdate,` that means it already run asynchronously, and I think we don't need to have another async action in `Container.setState`. If you use `Container.setState` in some controlled component like `input` you might getting the pointer jumping due to that async action. So I decided to create a function called `setStateSync` to bring it back. It might sound weird, but it works well in my projects :D

**Comment by johnbrett** [comment]
Thanks for the explanation @paul-phan!
